name: PR Workflow
run-name: Build and Test GoLang application
on: [pull_request]
jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Get to the app/ folder
        run: |
          cd app/
          pwd
      - name: Build the application
        run: go build
